CREATE TABLE R(
A INTEGER NOT NULL, 
B INTEGER
);
CREATE TABLE S(D INTEGER, E INTEGER, F DATE);

SELECT A, B FROM R;
SELECT A+B FROM R;
SELECT G FROM (SELECT A+B AS G FROM R);


SELECT * FROM R,S;
SELECT * FROM R ORDER BY A DESC;

SELECT * FROM R ORDER BY A DESC LIMIT 2;
SELECT * FROM R,S LIMIT 2;

SELECT R.*, S.E, S.F FROM R,S WHERE R.A > 3;

SELECT D, E FROM S
WHERE F >= '1994-01-01' AND F < '1994-01-03';


SELECT L_EXTENDEDPRICE, L_DISCOUNT, L_QUANTITY
FROM
    lineitem
WHERE
    L_SHIPDATE >= '2001-01-01'
    AND L_SHIPDATE < '2004-01-03'
   AND L_DISCOUNT > 0.05
    AND L_DISCOUNT < 0.07
    AND L_QUANTITY > 49
ORDER BY L_EXTENDEDPRICE
LIMIT 20;


SELECT C.*, N.n_name, R.r_name
FROM CUSTOMER C, NATION N, REGION R
WHERE N.n_nationkey = C.c_nationkey
     AND N.n_nationkey < 3
     AND C.c_mktsegment = 'FURNITURE'
     AND C.c_acctbal > 9995;


SELECT C.*, N.N_NAME, R.R_NAME
FROM CUSTOMER C, NATION N, REGION R
WHERE N.N_NATIONKEY = C.C_NATIONKEY
     AND N.N_NATIONKEY < 3
     AND C.MKTSEGMENT = 'FURNITURE'
     AND C.C_ACCTBAL > 9995;

     
CREATE TABLE CUSTOMER (
	C_CUSTKEY		INTEGER,
	C_NAME			STRING,
	C_ADDRESS		STRING,
	C_NATIONKEY		INTEGER NOT NULL, -- references N_NATIONKEY
	C_PHONE			STRING,
	C_ACCTBAL		DOUBLE,
	C_MKTSEGMENT	STRING,
	C_COMMENT		STRING
);


CREATE TABLE ORDERS (
	O_ORDERKEY		INTEGER,
	O_CUSTKEY		INTEGER NOT NULL, -- references C_CUSTKEY
	O_ORDERSTATUS	STRING,
	O_TOTALPRICE	DOUBLE,
	O_ORDERDATE		DATE,
	O_ORDERPRIORITY	STRING,
	O_CLERK			STRING,
	O_SHIPPRIORITY	INTEGER,
	O_COMMENT		STRING
);


CREATE TABLE LINEITEM (
	L_ORDERKEY		INTEGER NOT NULL, -- references O_ORDERKEY
	L_PARTKEY		INTEGER NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
	L_SUPPKEY		INTEGER NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
	L_LINENUMBER	INTEGER,
	L_QUANTITY		DOUBLE,
	L_EXTENDEDPRICE	DOUBLE,
	L_DISCOUNT		DOUBLE,
	L_TAX			DOUBLE,
	L_RETURNFLAG	STRING,
	L_LINESTATUS	STRING,
	L_SHIPDATE		DATE,
	L_COMMITDATE	DATE,
	L_RECEIPTDATE	DATE,
	L_SHIPINSTRUCT	STRING,
	L_SHIPMODE		STRING,
	L_COMMENT		STRING
);

CREATE TABLE NATION (
	N_NATIONKEY		INTEGER,
	N_NAME			STRING,
	N_REGIONKEY		INTEGER NOT NULL,  -- references R_REGIONKEY
	N_COMMENT		STRING
);

CREATE TABLE REGION (
	R_REGIONKEY	INTEGER,
	R_NAME		STRING,
	R_COMMENT	STRING
);     
     
     
SELECT D.C_NAME, D.N_NAME
FROM
(SELECT C.*, N.N_NAME, R.R_NAME
FROM CUSTOMER C, NATION N, REGION R
WHERE R.R_REGIONKEY = N.N_REGIONKEY
     AND N.N_NATIONKEY = C.C_NATIONKEY
     AND R.R_NAME = 'AMERICA') D,
ORDERS O, LINEITEM L
WHERE O.O_ORDERKEY = L.L_ORDERKEY
	AND O.O_CUSTKEY = D.C_CUSTKEY
	AND L.L_SHIPDATE < '1992-01-05'
ORDER BY D.C_NAME
LIMIT 5;


