CREATE TABLE R(
A INTEGER NOT NULL, 
B INTEGER
);
CREATE TABLE S(D INTEGER, E INTEGER, F DATE);

SELECT A, B FROM R;
SELECT A+B FROM R;
SELECT G FROM (SELECT A+B AS G FROM R);


SELECT * FROM R,S;
SELECT * FROM R ORDER BY A DESC;

SELECT * FROM R ORDER BY A DESC LIMIT 2;
SELECT * FROM R,S LIMIT 2;

SELECT R.*, S.E, S.F FROM R,S WHERE R.A > 3;

SELECT D, E FROM S
WHERE F >= '1994-01-01' AND F < '1994-01-03';


SELECT L_EXTENDEDPRICE, L_DISCOUNT, L_QUANTITY
FROM
    lineitem
WHERE
    L_SHIPDATE >= '2001-01-01'
    AND L_SHIPDATE < '2004-01-03'
   AND L_DISCOUNT > 0.05
    AND L_DISCOUNT < 0.07
    AND L_QUANTITY > 49
ORDER BY L_EXTENDEDPRICE
LIMIT 20;

